[workspace]

members = [
	"query-bpf",
	"hello-world"
]

[workspace.dependencies]
libbpf-rs = "*"
nix = { version = "0.26", default-features = false, features = ["net", "user"] }
libbpf-cargo = "*"
log = "*"
env_logger = "*"
